"""Exportable PDF report for an /api/analyze result.

The disclaimer at the top of every report is not boilerplate — it's the
single most important paragraph in this file. This tool produces
evidence-based scoring from real public data sources, not a clinical
diagnosis, and every exported document needs to say so plainly before
anyone downstream forgets that distinction.
"""

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

STYLES = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle("ReportTitle", parent=STYLES["Title"], fontSize=18, spaceAfter=4)
META_STYLE = ParagraphStyle("Meta", parent=STYLES["Normal"], fontSize=9, textColor=colors.HexColor("#555555"))
DISCLAIMER_STYLE = ParagraphStyle(
    "Disclaimer",
    parent=STYLES["Normal"],
    fontSize=9,
    leading=13,
    textColor=colors.HexColor("#7a1f1f"),
    backColor=colors.HexColor("#fdecec"),
    borderColor=colors.HexColor("#e0a0a0"),
    borderWidth=0.75,
    borderPadding=8,
)
SECTION_STYLE = ParagraphStyle("Section", parent=STYLES["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6)
CANDIDATE_NAME_STYLE = ParagraphStyle("CandidateName", parent=STYLES["Heading3"], fontSize=11, spaceAfter=2)
BODY_STYLE = ParagraphStyle("Body", parent=STYLES["Normal"], fontSize=9.5, leading=13)

DISCLAIMER_TEXT = (
    "<b>Research and informational tool — not a clinical diagnosis or treatment "
    "recommendation.</b> This report reflects evidence-based scoring computed from "
    "public data sources (Open Targets, ChEMBL) and locally-computed molecular "
    "properties (RDKit), combined with quantum-optimized ranking. It has not "
    "undergone clinical validation and must not replace the judgment of a "
    "qualified oncologist. Scores reflect data completeness and available "
    "evidence, not certainty of clinical outcome."
)


def _stage_label(stage):
    labels = {
        "APPROVAL": "Approved", "APPROVED": "Approved", "PHASE_4": "Approved",
        "PHASE_3": "Phase 3", "PHASE_2_3": "Phase 2/3", "PHASE_2": "Phase 2",
        "PHASE_1_2": "Phase 1/2", "PHASE_1": "Phase 1",
    }
    return labels.get((stage or "").upper(), stage or "Unknown")


def generate_pdf_report(analysis, requested_by=None):
    """analysis: the dict returned by analyze_routes._run_pipeline / the
    /api/analyze response body. requested_by: optional {"name","email"}
    of the user who generated the report, shown in the metadata block."""

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch,
        leftMargin=0.7 * inch, rightMargin=0.7 * inch,
    )

    story = []

    story.append(Paragraph("Quantum Drug Discovery", TITLE_STYLE))
    story.append(Paragraph("Evidence-Based Candidate Report", META_STYLE))
    story.append(Spacer(1, 10))
    story.append(Paragraph(DISCLAIMER_TEXT, DISCLAIMER_STYLE))
    story.append(Spacer(1, 14))

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    meta_lines = [
        f"<b>Target gene:</b> {analysis.get('gene', '—')} ({analysis.get('target_name', '—')})",
        f"<b>Cancer type:</b> {analysis.get('cancer_type', '—')}",
        f"<b>Generated:</b> {generated_at}",
    ]
    if requested_by:
        meta_lines.append(f"<b>Generated by:</b> {requested_by.get('name', '')} ({requested_by.get('email', '')})")
    meta_lines.append(f"<b>Data sources:</b> {analysis.get('source', 'Open Targets, ChEMBL, RDKit')}")

    for line in meta_lines:
        story.append(Paragraph(line, BODY_STYLE))

    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc")))

    candidates = analysis.get("candidates") or []

    if not candidates:
        story.append(Spacer(1, 14))
        story.append(Paragraph(
            analysis.get("message", "No candidates with documented evidence were found."),
            BODY_STYLE,
        ))
        doc.build(story)
        return buffer.getvalue()

    panel_ids = {c.get("chembl_id") for c in (analysis.get("diverse_panel") or [])}

    quantum = analysis.get("quantum_optimization")
    if quantum:
        story.append(Spacer(1, 12))
        story.append(Paragraph("Quantum-Optimized Panel Selection", SECTION_STYLE))
        story.append(Paragraph(
            f"Method: {quantum.get('method', 'QAOA')}. {quantum.get('caveat', '')}",
            BODY_STYLE,
        ))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Ranked Candidates", SECTION_STYLE))

    table_data = [["Rank", "Drug", "Score", "Confidence", "ADMET Risk", "Stage", "Panel"]]
    for i, c in enumerate(candidates, start=1):
        table_data.append([
            str(i),
            c.get("drug_name", "—"),
            f"{c.get('composite_score', 0)}/100",
            f"{round((c.get('confidence') or 0) * 100)}%",
            c.get("admet_risk_band", "Unknown"),
            _stage_label(c.get("evidence", {}).get("clinical_evidence", {}).get("stage")),
            "Yes" if c.get("chembl_id") in panel_ids else "",
        ])

    table = Table(table_data, colWidths=[0.4 * inch, 1.5 * inch, 0.7 * inch, 0.8 * inch, 0.9 * inch, 0.8 * inch, 0.5 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e2a4a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f7fa")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(table)

    story.append(Spacer(1, 16))
    story.append(Paragraph("Candidate Detail &amp; Evidence", SECTION_STYLE))

    for i, c in enumerate(candidates, start=1):
        is_panel = c.get("chembl_id") in panel_ids
        name_line = f"{i}. {c.get('drug_name', '—')}" + ("  [Quantum Panel]" if is_panel else "")
        story.append(Paragraph(name_line, CANDIDATE_NAME_STYLE))
        story.append(Paragraph(c.get("explanation", "No further evidence available."), BODY_STYLE))
        story.append(Spacer(1, 8))

    doc.build(story)
    return buffer.getvalue()
