"""add genomics_cache table

Revision ID: 72b65b1d9586
Revises: bee3f4eaba4c
Create Date: 2026-08-12 11:31:50.008239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b65b1d9586'
down_revision = 'bee3f4eaba4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genomics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genomics_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genomics_cache_cache_key'), ['cache_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomics_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genomics_cache_cache_key'))

    op.drop_table('genomics_cache')
    # ### end Alembic commands ###
